name: Label Issues Based on Template

on:
  issues:
    types: [opened, edited]

jobs:
  label-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue needs a label
        id: check_label
        run: |
          echo "Checking labels for issue #${{ github.event.issue.number }}"
          if [[ "${{ github.event.issue.body || '' }}" == *"I'm a GSSOC'24 contributor"* ]]; then
            echo "label=gssoc" >> $GITHUB_ENV
          elif [[ "${{ github.event.issue.body || '' }}" == *"I'm a VSOC'24 contributor"* ]]; then
            echo "label=VSoC'24" >> $GITHUB_ENV
          else
            echo "label=" >> $GITHUB_ENV
          fi

      - name: Apply Label
        if: env.label != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.label }}
