name: Label Issues Based on Template

on:
  issues:
    types: [opened, edited]

jobs:
  label-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue needs a label
        id: check_label
        run: |
          echo "Checking labels for issue #${{ github.event.issue.number }}"

          if [[ "${{ github.event.issue.body }}" == *"I'm a GSSOC'24 contributor"* ]]; then
            echo "::set-output name=label::gssoc"
          elif [[ "${{ github.event.issue.body }}" == *"I'm a VSOC'24 contributor"* ]]; then
            echo "::set-output name=label::VSoC'24"
          else
            echo "::set-output name=label::"
          fi

      - name: Apply Label
        if: steps.check_label.outputs.label != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.check_label.outputs.label }}
